### ISSUE TITLE
where is readFcnMatFile？

### ISSUE THREAD

**Issue by jorzen** [ThienHuynhThe/MCNet#1]
Error in deepsig_mcnet_running (line 5)
imdsTrain.ReadFcn = @readFcnMatFile;

where is readFcnMatFile？ How to use it？

**Comment by ThienHuynhThe** [comment]
please check the updated file.
copy it to the same folder. It is just a supportive function.
This function allows the matlab to read the high-dimension matrix array.

**Comment by jorzen** [comment]
thank you

**Comment by jorzen** [comment]
thank you
